### PR TITLE
add custom metrics file for fraud

### PR DESCRIPTION
**Pull request by jerryjliu**
Planning to define custom metrics in the fraud notebook (which is the primary entrypoint for users using the demo notebooks). It's the existing demo custom metric of average nulls per row.

### CODE REVIEW

**Review by asamant22 — APPROVED** [review]

**Comment by dhruvkedia** [comment]
@jerryjliu imo we shouldn't add it to the fraud notebook. The fraud notebook is the self serve notebook customers see for the first time. Complicating that notebook can confuse customers. We should instead add to say regression or ranking

**Comment by jerryjliu** [comment]
> @jerryjliu imo we shouldn't add it to the fraud notebook. The fraud notebook is the self serve notebook customers see for the first time. Complicating that notebook can confuse customers. We should instead add to say regression or ranking

ok! i was thinking regression actually. not a big deal, i'll change

**Comment by dhruvkedia** [comment]
> > @jerryjliu imo we shouldn't add it to the fraud notebook. The fraud notebook is the self serve notebook customers see for the first time. Complicating that notebook can confuse customers. We should instead add to say regression or ranking
> 
> ok! i was thinking regression actually. not a big deal, i'll change

Do you mean move the self serve notebook to regression? I'm okay with that as well. Or if you meant move custom metrics to regression - that also makes sense!

**Comment by jerryjliu** [comment]
> Do you mean move the self serve notebook to regression? I'm okay with that as well. Or if you meant move custom metrics to regression - that also makes sense!

Like move the custom metrics demo to the regression notebook (which is NYC TLC - it fits because that notebook is also showing nulls over time)

**Pull request closed without merging**
