### PR TITLE
add nlp classification

### PR DESCRIPTION
**Pull request by jerryjliu**
Context: I'm doing this so I can create a script which pulls tabular/image/nlp from ri-public-examples and runs stress tests, and uploads to a cluster. This can be used to seed new customer clusters with demo runs. 

General discussion items: 
- Since this repo is meant for SDK use, the examples contain the data/models, but they do not contain the json configs used for stress testing + firewall, since those would be specified in the notebook. BUT i left the test_config.json where specified, since that's a separate file, and we need a way to document what the specific test_config params for a specific run are. cc @dhruvkedia 
- I only included NLP classification (3 datasets) / Image detection (1 dataset). Is that fine for now? Is that too much / too little?

### CODE REVIEW

**Comment by dhruvkedia** [comment]
@jerryjliu how have we obtained these datasets? Any datasets included here in general should meet our legal guidance. Can you help provide some more information regarding this?

**Comment by hinthornw** [comment]
The size of this PR crashes chrome for me

**Comment by hinthornw** [comment]
Personally don't think we should be checking in all the raw images here - git doesn't excel for large files

**Comment by hinthornw** [comment]
For object detection, all the probabilities vectors don't seem to sum to 1. Is that an issue @KevLuo ?

**Comment by jerryjliu** [comment]
> @jerryjliu how have we obtained these datasets? Any datasets included here in general should meet our legal guidance. Can you help provide some more information regarding this?

This includes `arxiv`, `emotion_recognition`, and `sentiment_analysis` from the NLP trial examples, and `voc` from the Image trial examples. I believe they're all allowed under https://www.notion.so/robustintelligence/V13-Trial-Dataset-Licenses-41558b0e257948fa8e3662accb82bdac but also why I'm cc'ing @hinthornw @KevLuo 

> The size of this PR crashes chrome for me
> Personally don't think we should be checking in all the raw images here - git doesn't excel for large files

Yeah I'd heavily recommend not clicking into the "Files Changed" tab. @KevLuo is there a way to download raw image data instead of checking in large files? Alternatively I could just upload only the zip file and not the folder itself, since part of the reason its crashing is due to the quantity fof images

**Comment by hinthornw** [comment]
I also don't like including all the whitespace in data files. It uses a lot of space for something that's meant for a machine

**Comment by hinthornw** [comment]
> > @jerryjliu how have we obtained these datasets? Any datasets included here in general should meet our legal guidance. Can you help provide some more information regarding this?
> 
> This includes `arxiv`, `emotion_recognition`, and `sentiment_analysis` from the NLP trial examples, and `voc` from the Image trial examples. I believe they're all allowed under https://www.notion.so/robustintelligence/V13-Trial-Dataset-Licenses-41558b0e257948fa8e3662accb82bdac but also why I'm cc'ing @hinthornw @KevLuo
> 
> > The size of this PR crashes chrome for me
> > Personally don't think we should be checking in all the raw images here - git doesn't excel for large files
> 
> Yeah I'd heavily recommend not clicking into the "Files Changed" tab. @KevLuo is there a way to download raw image data instead of checking in large files? Alternatively I could just upload only the zip file and not the folder itself, since part of the reason its crashing is due to the quantity of images

Maybe we could use a load_image_loader? E.g., python file that downloads the raw data the first time it's called. 

I'm not sure if we've really settled on a clean interface for this type of thing actually

**Comment by hinthornw** [comment]
There's a lot of unused code for the detection model. Like `InfiniteDataLoader` is clearly never used here

**Comment by hinthornw** [comment]
Why do we have all the zip files here as well as the unzipped folders? e.g., arxiv.zip, emotion_recognition.zip, sentiment_analysis.zip

**Comment by hinthornw** [comment]
Rest seems ok to me!

**Comment by n8cha** [comment]
> Why do we have all the zip files here as well as the unzipped folders? e.g., arxiv.zip, emotion_recognition.zip, sentiment_analysis.zip

Use case for this repo is to be able to pull specific datasets, but GitHub doesn't really have a good way to download a folder from a repo (unless you wanna git clone the whole thing).

The zips are a workaround to be able to do this:
image

**Comment by n8cha** [comment]
Jw--why do we have this yolov3 code copied here? Is that not something we can import?

image

On the topic of imports, is it worth adding `requirements.txt` to each subfolder (or each `model/` subfolder)?

**Comment by jerryjliu** [comment]
> I also don't like including all the whitespace in data files. It uses a lot of space for something that's meant for a machine

Hmm @hinthornw do you think space is a big issue? I don't mind whitespace actually since it makes the data a lot more readable. 

> There's a lot of unused code for the detection model. Like `InfiniteDataLoader` is clearly never used here

Remember @KevLuo saying there were unused files but was going to take a lot of time to remove all of them, will defer to him to decide if cleaning this up further is worth the cost. 

> Jw--why do we have this yolov3 code copied here? Is that not something we can import?

Will defer to @KevLuo but seems like when we load a model through PyTorch hub there's a bunch of associated files that also need to be present (the model and utils directory) 

> On the topic of imports, is it worth adding `requirements.txt` to each subfolder (or each `model/` subfolder)?

IMO don't think adding requirements.txt to each subfolder makes sense BUT there's the `trial_model_requirements.txt` in nlp_examples in the trial bundle that I can add... @KevLuo is there a similar one for images?

**Comment by jerryjliu** [comment]
Also some more context: Seems like eventually we want to get rid of the trial bundle entirely in favor of the demo notebooks? (cc @dhruvkedia @n8cha for confirmation). So all the datasets/models would be migrated here. Food for thought @KevLuo @hinthornw + @asamant22 (since you're working on the NLP/Image demo notebooks )

**Comment by hinthornw** [comment]
> Hmm @hinthornw do you think space is a big issue? I don't mind whitespace actually since it makes the data a lot more readable.

Yeah git is slow with data files and including whitespace more than doubles the required space. Querying is really easy using any of your favorite command line tools. I don't think we should inflate all our data for such a marginal benefit

> Remember @KevLuo saying there were unused files but was going to take a lot of time to remove all of them, will defer to him to decide if cleaning this up further is worth the cost.

Hm. True, but this is a public repo. We need to hold ourselves to high standards for this kind of thing vs. experiment branches.

**Comment by KevLuo** [comment]
> For object detection, all the probabilities vectors don't seem to sum to 1. Is that an issue @KevLuo ?

@hinthornw nope it's not. reason for this is because model i'm using only outputs confidence for argmax class. since i was lazy i didn't try to spend too much time to try to access probabilities for everything else. and we don't have a check in the code that the probs sum to 1.

**Comment by hinthornw** [comment]
> > For object detection, all the probabilities vectors don't seem to sum to 1. Is that an issue @KevLuo ?
> 
> @hinthornw nope it's not. reason for this is because model i'm using only outputs confidence for argmax class. since i was lazy i didn't try to spend too much time to try to access probabilities for everything else. and we don't have a check in the code that the probs sum to 1.

Shouldn't we just assign 1-(argmax_prob) as a uniform prob for the other classes then?

**Comment by hinthornw** [comment]
> > > For object detection, all the probabilities vectors don't seem to sum to 1. Is that an issue @KevLuo ?
> > 
> > 
> > @hinthornw nope it's not. reason for this is because model i'm using only outputs confidence for argmax class. since i was lazy i didn't try to spend too much time to try to access probabilities for everything else. and we don't have a check in the code that the probs sum to 1.
> 
> Shouldn't we just assign 1-(argmax_prob) as a uniform prob for the other classes then?

Seems like bad communication to have our one detection example include 'probabilities' vectors that aren't really correct.

**Comment by dhruvkedia** [comment]
> > @jerryjliu how have we obtained these datasets? Any datasets included here in general should meet our legal guidance. Can you help provide some more information regarding this?
> 
> This includes `arxiv`, `emotion_recognition`, and `sentiment_analysis` from the NLP trial examples, and `voc` from the Image trial examples. I believe they're all allowed under https://www.notion.so/robustintelligence/V13-Trial-Dataset-Licenses-41558b0e257948fa8e3662accb82bdac but also why I'm cc'ing @hinthornw @KevLuo
> 
> > The size of this PR crashes chrome for me
> > Personally don't think we should be checking in all the raw images here - git doesn't excel for large files
> 
> Yeah I'd heavily recommend not clicking into the "Files Changed" tab. @KevLuo is there a way to download raw image data instead of checking in large files? Alternatively I could just upload only the zip file and not the folder itself, since part of the reason its crashing is due to the quantity fof images

@jerryjliu 
1) arxiv is good
2) emotion_recognition is based on Hugging Face. In [this doc](https://www.notion.so/robustintelligence/V13-Trial-Dataset-Licenses-41558b0e257948fa8e3662accb82bdac#45d86fcb9e78476699b048e94c6a1364) it says questionable. @hinthornw do you know more about Hugging Face license information? If not I can take a look
3) sentiment_analysis - no mention anywhere. What is the source of this dataset?
4) voc - no mention anywhere. What is the source of this dataset?

**Comment by dhruvkedia** [comment]
> Also some more context: Seems like eventually we want to get rid of the trial bundle entirely in favor of the demo notebooks? (cc @dhruvkedia @n8cha for confirmation). So all the datasets/models would be migrated here. Food for thought @KevLuo @hinthornw + @asamant22 (since you're working on the NLP/Image demo notebooks )

From my perspective yes. But I'd leave the final decision up to @n8cha and @hwchase17.

**Comment by hinthornw** [comment]
> > > @jerryjliu how have we obtained these datasets? Any datasets included here in general should meet our legal guidance. Can you help provide some more information regarding this?
> > 
> > 
> > This includes `arxiv`, `emotion_recognition`, and `sentiment_analysis` from the NLP trial examples, and `voc` from the Image trial examples. I believe they're all allowed under https://www.notion.so/robustintelligence/V13-Trial-Dataset-Licenses-41558b0e257948fa8e3662accb82bdac but also why I'm cc'ing @hinthornw @KevLuo
> > > The size of this PR crashes chrome for me
> > > Personally don't think we should be checking in all the raw images here - git doesn't excel for large files
> > 
> > 
> > Yeah I'd heavily recommend not clicking into the "Files Changed" tab. @KevLuo is there a way to download raw image data instead of checking in large files? Alternatively I could just upload only the zip file and not the folder itself, since part of the reason its crashing is due to the quantity fof images
> 
> @jerryjliu
> 
> 1. arxiv is good
> 2. emotion_recognition is based on Hugging Face. In [this doc](https://www.notion.so/robustintelligence/V13-Trial-Dataset-Licenses-41558b0e257948fa8e3662accb82bdac#45d86fcb9e78476699b048e94c6a1364) it says questionable. @hinthornw do you know more about Hugging Face license information? If not I can take a look
> 3. sentiment_analysis - no mention anywhere. What is the source of this dataset?
> 4. voc - no mention anywhere. What is the source of this dataset?

Emotion rec is: https://github.com/dair-ai/emotion_dataset - we should probably stop using this. No lawyer ever reviewed the decision though
Sentiment is: https://ai.stanford.edu/~amaas/data/sentiment/  - no license but should be OK. IANAL

**Comment by KevLuo** [comment]
i'm gonna talk to dhruv offline about legal stuff because it's clogging up this PR and there's like 3 separate comment threads on this PR

**Comment by hinthornw** [comment]
> Use case for this repo is to be able to pull specific datasets, but GitHub doesn't really have a good way to download a folder from a repo (unless you wanna git clone the whole thing).

> The zips are a workaround to be able to do this:

Personal vote would be then to not use github for this

**Comment by dhruvkedia** [comment]
> > Use case for this repo is to be able to pull specific datasets, but GitHub doesn't really have a good way to download a folder from a repo (unless you wanna git clone the whole thing).
> 
> > The zips are a workaround to be able to do this:
> 
> Personal vote would be then to not use github for this

@hinthornw @jerryjliu @n8cha 
Alternative approach i can think of is storing these datasets on a publicly accessible s3 bucket. What do you folks think? When I was creating the self serve demo, I saw other folks using cloud storage buckets to store the data.

**Comment by n8cha** [comment]
> > Use case for this repo is to be able to pull specific datasets, but GitHub doesn't really have a good way to download a folder from a repo (unless you wanna git clone the whole thing).
> 
> > The zips are a workaround to be able to do this:
> 
> Personal vote would be then to not use github for this

It all started with a slack thread ..

**Comment by hinthornw** [comment]
> > > Use case for this repo is to be able to pull specific datasets, but GitHub doesn't really have a good way to download a folder from a repo (unless you wanna git clone the whole thing).
> > 
> > > The zips are a workaround to be able to do this:
> > 
> > 
> > Personal vote would be then to not use github for this
> 
> It all started with a slack thread ..

Hm. OK I'm fine doing this for now until we get close to 1 GB worth of data for this repo.

funny, GitHub recommends DropBox still :P
https://docs.github.com/en/repositories/working-with-files/managing-large-files/about-large-files-on-github

**Comment by jerryjliu** [comment]
Ok this is a long discussion so in the interest of TODO's: 
- I'm removing all image stuff in this PR since we're stil figuring out license issues. That should remove all concerns about chrome crashing + the extraneous detection files for now though we obv need to address in the future. 
- For NLP, I'm removing emotion recognition for now. For the rest of the data, @hinthornw if you want i can collapse whitespace 

that sounds good?

**Comment by jerryjliu** [comment]
Updated cc @hinthornw, PTAL!

**Review by asamant22 — CHANGES_REQUESTED** [review]
Remove the tests_config.json

**Review by hinthornw — APPROVED** [review]

**Comment by jerryjliu** [comment]
> Remove the tests_config.json

Actually I purposely left it in there so that we could embed the test_config as a dict in the main run config...

**Review by asamant22 — APPROVED** [review]

**Pull request merged**
